
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      
  backend:
    build:
      context: ./backend
    depends_on:
      - mongo
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/myMernApp
      - PORT=8888
      - HOST=0.0.0.0
    ports:
      - "8888:8888"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    extra_hosts:
      - "localhost:host-gateway"

volumes:
  mongo-data:
